name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kushan2000
          password: mrKMR@921

      - name: Build Docker image
        run: docker build -t kushan2000/cicddemo2:latest .

      - name: Push Docker image to Docker Hub
        run: docker push kushan2000/cicddemo2:latest

  sonarcloud:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.organization=testsonar921
              -Dsonar.projectKey=GitHub-actions2